### ISSUE TITLE
电脑网页开启手机模式，一直定位不到怎么解决，已经开启定位了

### ISSUE THREAD

**Issue by ytianzaishui** [gaojingran/react-eleme#1]
![image](https://user-images.githubusercontent.com/18025841/40295605-7c07989a-5d0c-11e8-8da5-9c0e6f65a4b6.png)
![image](https://user-images.githubusercontent.com/18025841/40295612-83d4a1a8-5d0c-11e8-992e-1316b1b32628.png)

**Comment by ytianzaishui** [comment]
本地运行项目，已经处理了mac和window系统换行的问题，一直出现如下状况

![image](https://user-images.githubusercontent.com/18025841/40295596-7047e294-5d0c-11e8-9d3c-71bbb1db1732.png)

**Comment by JuneHello** [comment]
一直出现楼上的情况，window下的，，，，问一下作者是npm start 为啥打开不了服务啊，，不像vue脚手架那样吗

**Comment by super918180** [comment]
@Chen-WeiZhen  I delete ""postcss-viewport-units": {}," in '.postcssrc.js',then it runs well and without warning.
